# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np 

arr=np.random.randint(1,20,size=(5,5))

arr[:,2]=1 
arr

array([[10, 15,  1, 11, 11],
       [ 2,  3,  1,  4, 15],
       [16,  8,  1, 11,  6],
       [ 8, 17,  1,  3, 11],
       [19, 14,  1, 13,  1]], dtype=int32)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr=np.random.randint(1,16,size=(4,4))

## to fill diagonal elements
np.fill_diagonal(arr,0)
arr

array([[ 0,  8, 13, 12],
       [12,  0,  7,  3],
       [15,  2,  0,  7],
       [10,  8, 11,  0]], dtype=int32)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
import numpy as np

arr=np.random.randint(1,36,size=(6,6))

print(arr)
arr[2:,2:5]

[[18  2 12 27 18 19]
 [23 31 31  3 27 11]
 [18 14  9 28 33 20]
 [23 21 13 13 12  2]
 [ 3 15 14  6  7  1]
 [19 27 24  5 31  5]]


array([[ 9, 28, 33],
       [13, 13, 12],
       [14,  6,  7],
       [24,  5, 31]], dtype=int32)

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
## create a numpy array
arr=np.random.randint(1,100,size=(5,5))

print("Original Array : \n")
print(arr) 


##concatining the border elements 
borderElements=np.concat((arr[0],arr[:,-1],arr[-1],arr[:,0]))
print("border Elements: \n ")
print(borderElements)

Original Array : 

[[43 38 52 86  2]
 [43 21 63 84 46]
 [69 87 45 24 82]
 [88 10  2 60 67]
 [69 44 85 86 27]]
border Elements: 
 
[43 38 52 86  2  2 46 82 67 27 69 44 85 86 27 43 43 69 88 69]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1=np.random.randint(1,100,size=(3,4))
arr2=np.random.randint(1,200,size=(3,4))


np.random.seed(1000) 
print("Array 1 ")
print(arr1)
print("Array 2 ")
print(arr2)

print("Addition : \n")
print(arr1+arr2)  


print("Substation : \n")
print(arr1-arr2) 


print("Mutliplication: \n")
print(arr1 * arr2*arr1) 

print("Divison : \n")
print((arr1//arr2)*arr2)



Array 1 
[[66 65 49 24]
 [70 60 64 10]
 [14 45 13 35]]
Array 2 
[[165   8  35 177]
 [107   9 151  95]
 [  9 113  14   9]]
Addition : 

[[231  73  84 201]
 [177  69 215 105]
 [ 23 158  27  44]]
Substation : 

[[ -99   57   14 -153]
 [ -37   51  -87  -85]
 [   5  -68   -1   26]]
Mutliplication: 

[[718740  33800  84035 101952]
 [524300  32400 618496   9500]
 [  1764 228825   2366  11025]]
Divison : 

[[ 0 64 35  0]
 [ 0 54  0  0]
 [ 9  0  0 27]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr=np.random.randint(1,17,size=(4,4)) 
np.random.seed(300)

print("Original Array : \n")
print(arr)

row_sum=np.sum(arr,axis=1)
col_sum=np.sum(arr,axis=0)

print("row sum : \n")
print(row_sum) 

print("column sum")
print(col_sum)

Original Array : 

[[ 4  8  8  1]
 [12 15 13  2]
 [14  1 10 14]
 [ 9 10 13 12]]
row sum : 

[21 42 39 44]
column sum
[39 34 44 29]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [8]:
arr=np.random.randint(1,26,size=(5,5))

print("Mean :",end="")
print(np.mean(arr)) 
print("Median : ",end="")
print(np.median(arr)) 
print("Standard deviation: ",end="")
print(np.std(arr)) 
print("variance : ",end="")
print(np.var(arr))

Mean :12.88
Median : 11.0
Standard deviation: 7.084179557295255
variance : 50.1856


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
## calculaion of normalized array calculation using z score
arr = np.random.randint(1,10,size=(3,3))
print("Original Array: \n")
print(arr)

mean = np.mean(arr)
std = np.std(arr)

normalized_array = (arr - mean) / std
print("normalized array")
print(normalized_array)


Original Array: 

[[8 5 7]
 [4 1 5]
 [9 2 6]]
normalized array
[[ 1.11803399 -0.08944272  0.71554175]
 [-0.49193496 -1.69941166 -0.08944272]
 [ 1.52052622 -1.29691943  0.31304952]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
arr1=np.random.randint(1,100,size=(3,3))
arr2=np.random.randint(1,100,size=(3,))

print("original array 1 ")
print(arr1)
print("Original array 2")
print(arr2)
brodcasted_array=arr1+arr2 
print("Broadcasted Array")
print(brodcasted_array)

original array 1 
[[14 56 24]
 [56 44 96]
 [99 71 58]]
Original array 2
[ 3 11 34]
Broadcasted Array
[[ 17  67  58]
 [ 59  55 130]
 [102  82  92]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr1=np.random.randint(1,100,size=(3,3))
arr2=np.random.randint(1,100,size=(3,)) 


## substract from all rows
brodcasted_array=arr1-arr2[:,np.newaxis]
print(brodcasted_array)

[[-81 -68 -57]
 [ 31  28  28]
 [ 25   5  95]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
arr = np.array([[1,2,3],
                [0,1,4],
                [5,6,0]])

print("Determinant:")
print(np.linalg.det(arr))

print("Inverse:")
print(np.linalg.inv(arr)) 

print('eigen values')
print(np.linalg.eigvals(arr))


Determinant:
0.9999999999999964
Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
eigen values
[-5.2296696  -0.02635282  7.25602242]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
arr1=np.random.randint(1,16,size=(4,4))
arr2=np.random.randint(1,16,size=(4,4))

print(arr1)
print(arr2)

multiplied_array=np.dot(arr1,arr2)
print(multiplied_array)

[[15  3  9  4]
 [10  9  4 12]
 [ 2  6 14 11]
 [10  2  5 11]]
[[13  7  1  3]
 [13  1 12 10]
 [ 4  6  1 11]
 [15 14  9 11]]
[[330 218  96 218]
 [443 271 230 296]
 [325 258 187 341]
 [341 256 138 226]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr=np.random.randint(1,10,size=(3,3))
print("Original Array")
print(arr) 

reshaped_array=arr.reshape((1,9)) 
print("reshaped array : \n")
print(reshaped_array)

Original Array
[[3 9 5]
 [5 7 9]
 [9 4 7]]
reshaped array : 

[[3 9 5 5 7 9 9 4 7]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
arr=np.random.randint(1,100,size=(5,5))

## ORIGINAL ARRAy 
print("Original array: \n")
print(arr)


flatten_array=arr.flatten()
print("flatten_array : \n",flatten_array) 


flatten_reshaped_array=flatten_array.reshape((5,5))

print("flatten reshaped array : \n ",flatten_reshaped_array)

Original array: 

[[39 69 71  4 41]
 [83 83 29 12 81]
 [53 99 22 59 93]
 [65 18 76 59  4]
 [33 29 22 89 54]]
flatten_array : 
 [39 69 71  4 41 83 83 29 12 81 53 99 22 59 93 65 18 76 59  4 33 29 22 89
 54]
flatten reshaped array : 
  [[39 69 71  4 41]
 [83 83 29 12 81]
 [53 99 22 59 93]
 [65 18 76 59  4]
 [33 29 22 89 54]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [16]:

arr=np.random.randint(1,1000,size=(5,5))

print("Original Array : \n",arr)

extract_fancy_index=arr[[0,0,-1,-1],[0,-1,-1,0]]

print("Extracted fancy index: \n")
print(extract_fancy_index)

Original Array : 
 [[809 578 181 652 910]
 [926 432 177 575 756]
 [862 376 217 197 931]
 [210 224 507 275 555]
 [360  22 740 188 243]]
Extracted fancy index: 

[809 910 243 360]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [17]:
arr=np.random.randint(1,100,size=(4,4))


print("Original Array: \n")
print(arr)

arr[arr>10]=10
print(arr)

Original Array: 

[[ 9 52 49 93]
 [45 81 69 67]
 [53 92 88 93]
 [61 15 46 53]]
[[ 9 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
students={
    "rahul":{'age':20,'marks':300,'sex':'M'},
    "vivek":{'age':3,'marks':30,'sex':'F'},
    "pranneth":{'age':50,'marks':0,'sex':'F'}
}
print(students)
students=dict(sorted(students.items(),key=lambda x : x[1]["age"]))
print("sorted students by age :\n",students) 

import pandas as pd 

df=pd.DataFrame(students) 
print("data frame : \n",df)



## here u10,i4,f4 denotes the data types in the numpy arrays

data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data) 


sorted_data=np.sort(data,order='age')
print("Sorted Array : \n")
print(sorted_data)

{'rahul': {'age': 20, 'marks': 300, 'sex': 'M'}, 'vivek': {'age': 3, 'marks': 30, 'sex': 'F'}, 'pranneth': {'age': 50, 'marks': 0, 'sex': 'F'}}
sorted students by age :
 {'vivek': {'age': 3, 'marks': 30, 'sex': 'F'}, 'rahul': {'age': 20, 'marks': 300, 'sex': 'M'}, 'pranneth': {'age': 50, 'marks': 0, 'sex': 'F'}}
data frame : 
       vivek rahul pranneth
age       3    20       50
marks    30   300        0
sex       F     M        F
Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted Array : 

[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
import numpy as np

# Define a structured data type with two integer fields: x and y
data_type = [('x', 'i4'), ('y', 'i4')]

# Create a structured NumPy array using the above data type
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)

print("Original Array:\n")
print(data)

print("\nEuclidean distance:\n")

# Compute pairwise Euclidean distance between all points
# Explanation:
# data['x'] gives all x-coordinates → [1, 3, 5]
# data['y'] gives all y-coordinates → [2, 4, 6]
#
# data['x'][:, np.newaxis] converts shape from (3,) to (3,1)
# so broadcasting can happen with data['x'] which is (3,)
#
# Formula: distance = sqrt( (x1 - x2)^2 + (y1 - y2)^2 )
# Broadcasting automatically computes this for all pairs
distance = np.sqrt(
    (data['x'][:, np.newaxis] - data['x']) ** 2 +
    (data['y'][:, np.newaxis] - data['y']) ** 2
) 

print(distance)


Original Array:

[(1, 2) (3, 4) (5, 6)]

Euclidean distance:

[1 3 5]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [34]:
import numpy.ma as ma 
array=np.random.randint(1,15,size=(4,4))

print("Original arary : \n")
print(array)


masked_array=ma.masked_greater(array,10)
print("Masked array : \n")
print(masked_array)
masked_sum=masked_array.sum() 
print("Masked Sum : \n ",masked_sum)


Original arary : 

[[13  2  6  2]
 [ 7  4  6  4]
 [ 3  3  4  3]
 [ 2  8  1 14]]
Masked array : 

[[-- 2 6 2]
 [7 4 6 4]
 [3 3 4 3]
 [2 8 1 --]]
Masked Sum : 
  55


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
arr=np.random.randint(1,100,size=(3,3))
print("Orignal array : \n",arr)

masked_array=mp.