### numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

| Feature / Aspect            | Traditional Python List                                    | NumPy Array                                                       |
| --------------------------- | ---------------------------------------------------------- | ----------------------------------------------------------------- |
| **Data Type Support**       | Stores mixed data types (heterogeneous)                    | Stores only one data type (homogeneous)                           |
| **Memory Usage**            | High (each element is a Python object)                     | Low (compact, fixed-type storage)                                 |
| **Speed / Performance**     | Slower for numerical operations                            | Much faster due to vectorization and C backend                    |
| **Mathematical Operations** | No element-wise operations                                 | Supports element-wise operations directly                         |
| **Dimensionality**          | 1D by default, nested lists required for higher dimensions | Supports multi-dimensional arrays naturally (1D, 2D, 3D...)       |
| **Slicing & Indexing**      | Only basic slicing                                         | Advanced slicing, boolean indexing, fancy indexing                |
| **Broadcasting**            | Not supported                                              | Fully supports broadcasting                                       |
| **Memory Layout**           | Elements scattered in memory                               | Stored in contiguous memory blocks                                |
| **Functions & Tools**       | Limited built-in functionality                             | Extensive mathematical, statistical, and linear algebra functions |
| **Use Case**                | General-purpose data storage                               | Scientific computing, ML, data analysis                           |



In [2]:
!pip install numpy

In [3]:
import numpy as np 

## create an array using numpy 

##create a 1d array 

arr1=np.array([1,2,3,4,5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
arr1.shape

(5,)

In [7]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape((2,3))  # 2 rows and 5 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,67]])

In [9]:
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 2  3  4  5 67]]


(2, 5)

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## identiry matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
## attributes of numpy array

arr=np.array([1,2,4,5,6]) 


print("Array : ",arr)
print("shape : ",arr.shape)
print("NUmber of dimensions : ",arr.ndim) 
print("Size ( number of elements in the array ) : " , arr.size)
print("Data type :",arr.dtype)
print("Item size (in bytes): ",arr.itemsize)

Array :  [1 2 4 5 6]
shape :  (5,)
NUmber of dimensions :  1
Size ( number of elements in the array ) :  5
Data type : int64
Item size (in bytes):  8


In [14]:
## numpy vectorized operations 



arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


## element wise addion 

print("addition : ",arr1+arr2) 
print("substraction : ",arr1-arr2)
print("multiplication : ",arr1*arr2)
print("division : ",arr1/arr2)

addition :  [11 22 33 44 55]
substraction :  [ -9 -18 -27 -36 -45]
multiplication :  [ 10  40  90 160 250]
division :  [0.1 0.1 0.1 0.1 0.1]


In [15]:
## universal functions 


arr=np.array([2,3,4,5,6])

print(np.sqrt(arr)) 

## exponential 

print(np.exp(arr)) 

#sine 
print(np.sin(arr)) 

#natural log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [16]:
## array slicing and indexing 


arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
print("array : \n",arr) 


#pick an element
print(arr[0][0]) 
print(arr[0,0]) 


## accessing some elements
print(arr[1:,2:]) 

array : 
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
1
1
[[ 7  8  9]
 [12 13 14]]


In [17]:
arr[1:]=100 
print(arr)

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [18]:
##statistical concepts normalization 
## to have a mean of 0 and standard deviation of 1 

## calculate the mean and standard deviation 

data=np.array([1,2,3,4,5])

#calculate the mean and standarad deviation 
mean=np.mean(data)
std_dev=np.std(data)

#normalize the data
normalized_data=(data-mean)/std_dev
print("normalized data : ",normalized_data)


normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
## mean 

mean=np.mean(data)
print("mean : ",mean)
## median 

median=np.median(data)
print("median : ",median)

## standard deviation 
standard_deviation=np.std(data)
print("standard deviaiton : ",standard_deviation)


##variance 
var=np.var(data)
print("variance : ",var)

mean :  3.0
median :  3.0
standard deviaiton :  1.4142135623730951
variance :  2.0


In [30]:
## LOGICAL  operations 

data=np.array([1,2,3,4,5,6,7,8,9]) 

data[(data>5) & (data<8)]
data[(data>5) | (data<8)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])